MODULE GENERATED_MODULE
  USE ISO_C_BINDING
  USE OP2_C
  USE cudaConfigurationParams
  USE CUDAFOR
  TYPE  :: real8Array_integer4Array_opDatDimensions
  INTEGER(kind=4) :: opDat1Dimension
  END TYPE real8Array_integer4Array_opDatDimensions

  TYPE  :: real8Array_integer4Array_variableSizes
  INTEGER(kind=4) :: opDat1Size
  INTEGER(kind=4) :: opDat2Size
  END TYPE real8Array_integer4Array_variableSizes

  LOGICAL :: isFirstTime_real8Array_integer4Array = .TRUE.
  TYPE ( real8Array_integer4Array_variableSizes ) , DEVICE :: sizes_real8Array_integer4Array
  TYPE ( real8Array_integer4Array_opDatDimensions ) , DEVICE :: dimensions_real8Array_integer4Array
  CONTAINS

  attributes(device) SUBROUTINE s3750292099(x, y)
    IMPLICIT NONE
    REAL(kind=8), DIMENSION(*), DEVICE :: x
    INTEGER(kind=4), DIMENSION(*), DEVICE :: y
    x(1) = x(1) + y(1) + y(2)
  END SUBROUTINE

  attributes(global) SUBROUTINE s2339751590(dimensions_s3750292099, sizes_s3750292099, opDat1, opDat2, setSize, warpSiz&
  &e)
    IMPLICIT NONE
    TYPE ( real8Array_integer4Array_opDatDimensions ) , DEVICE :: dimensions_s3750292099
    TYPE ( real8Array_integer4Array_variableSizes ) , DEVICE :: sizes_s3750292099
    REAL(kind=8), DIMENSION(0:sizes_s3750292099%opDat1Size - 1), DEVICE :: opDat1
    INTEGER(kind=4), DIMENSION(0:1), DEVICE :: opDat2
    INTEGER(kind=4), VALUE :: setSize
    INTEGER(kind=4), VALUE :: warpSize
    REAL(kind=8), DIMENSION(0:3) :: opDat1Local
    REAL(kind=8), DIMENSION(0:*), SHARED :: sharedFloat8
    INTEGER(kind=4) :: i1
    INTEGER(kind=4) :: i2
    INTEGER(kind=4) :: threadID
    INTEGER(kind=4) :: offset
    INTEGER(kind=4) :: offset2
    INTEGER(kind=4) :: nelems
    threadID = mod(threadidx%x - 1,  warpSize)
    offset = (threadidx%x - 1) / warpSize / 8

    DO i1 = 0, 3, 1
      opDat1Local(i1) = opDat1Local(i1 + blockidx%x * 4)
    END DO

    DO i1 = threadidx%x - 1 + (blockidx%x - 1) * blockdim%x, setSize - 1, blockdim%x * griddim%x
      offset = i1 - threadID
      nelems = min(warpSize,  setSize - offset)
      CALL s3750292099(opDat1Local,  opDat2(0:sizes_s3750292099%opDat2Size - 1))

      DO i2 = 0, dimensions_s3750292099%opDat1Dimension - 1, 1
        sharedFloat8(offset + (i2 + threadID * dimensions_s3750292099%opDat1Dimension)) = opDat1Local(i2)
      END DO

      DO i2 = 0, dimensions_s3750292099%opDat1Dimension - 1, 1
        opDat1(threadID + (i2 * nelems + offset * dimensions_s3750292099%opDat1Dimension)) = sharedFloat8(offset + (thr&
        &eadID + i2 * nelems))
      END DO

    END DO

  END SUBROUTINE

  attributes(host) SUBROUTINE s2168928953(userSubroutine, set, opDat1, opIndirection1, opMap1, opAccess1, opDat2, opInd&
  &irection2, opMap2, opAccess2)
    IMPLICIT NONE
    character(len=24), INTENT(IN) :: userSubroutine
    TYPE ( op_set ) , INTENT(IN) :: set
    TYPE ( op_dat ) , INTENT(IN) :: opDat1
    INTEGER(kind=4), INTENT(IN) :: opIndirection1
    TYPE ( op_map ) , INTENT(IN) :: opMap1
    INTEGER(kind=4), INTENT(IN) :: opAccess1
    TYPE ( op_dat ) , INTENT(IN) :: opDat2
    INTEGER(kind=4), INTENT(IN) :: opIndirection2
    TYPE ( op_map ) , INTENT(IN) :: opMap2
    INTEGER(kind=4), INTENT(IN) :: opAccess2
    INTEGER(kind=4) :: opDat1Size
    INTEGER(kind=4) :: opDat2Size
    REAL(kind=8), DIMENSION(:), DEVICE, ALLOCATABLE :: opDat1Device
    INTEGER(kind=4), DIMENSION(:), DEVICE, ALLOCATABLE :: opDat2Device
    INTEGER(kind=4) :: nblocks
    INTEGER(kind=4) :: nthreads
    INTEGER(kind=4) :: nshared
    INTEGER(kind=4) :: threadSynchRet
    INTEGER(kind=4) :: warpSize

    IF (isFirstTime_real8Array_integer4Array .EQV. .TRUE.) THEN
      dimensions_real8Array_integer4Array%opDat1Dimension = opDat1%dim
      sizes_real8Array_integer4Array%opDat1Size = opDat1%dim * opDat1%set%size
      sizes_real8Array_integer4Array%opDat2Size = opDat2%dim
      isFirstTime_real8Array_integer4Array = .FALSE.
    END IF

    nblocks = 200
    nthreads = 128
    warpSize = OP_WARP_SIZE
    nshared = 32
    nshared = nshared * nthreads
    opDat1Size = opDat1%dim * opDat1%set%size
    opDat2Size = opDat2%dim
    CALL c_f_pointer(opDat1%dat_d,  opDat1Device,  (/opDat1Size/))
    CALL c_f_pointer(opDat2%dat_d,  opDat2Device,  (/opDat2Size/))
    CALL s2339751590<<<nblocks, nthreads, nshared>>>(dimensions_real8Array_integer4Array,  sizes_real8Array_integer4Arr&
    &ay,  opDat1Device,  opDat2Device,  set%size,  warpSize)
    threadSynchRet = cudaThreadSynchronize()
  END SUBROUTINE

END MODULE GENERATED_MODULE

